---
title: "Foundations in R Assignment pt 1"
author: "Amanda Mae Woodward"
date: "2026-09-24"
output: html_document
---

For your first R Assignment, complete the questions below. Remember, weekly assignments are graded based on attempts and accuracy, so it's ok if you don't get everything immediately. Please submit your answers by 1) updating this file in your GitHub repository and 2) uploading a .html file of the assignment to this repository. Please submit a link to the repository on Canvas. 

# Variables, Vectors, Lists, and Data frames

1. Create a vector called score that starts at 1 and contains every 9th number between 1 and 100. 
2. Create a list called participants that contains the participants 1 - 12. 
3. Create a list called condition that alternates the words control and experimental six times, for a total of 12 words.
4. Create a dataframe from the variables in #1-3. 
5. Take the mean of the score column from your dataframe.

# Using data frames 

6. Open the penguins dataframe. Print the dataframe.  
7. Create a subset of data for Adelie penguins. 
8. Summarize this subset of data. 
8. Create a dataframe that contains penguins with a bill length greater than or equal to the average bill length. 
9. How many penguins are in this subset? 

# More dataset use
10. Load the tidyverse library if you haven't already done so.
12. Create a new dataframe that has diamonds greater than 1 carat and an ideal cut. 
13. Find the mean and standard deviation of price for this new dataset. 
14. Create another new dataframe from the original diamonds dataset that includes all diamonds with a price between $2500 and $5000. 
15. Which color occurs most in this new subset? 